version: 2
jobs:
  build:
    docker:
    - image: node:latest
    steps:
    - checkout
    - run: npm version
    - restore_cache:
        name: Restore  NPM Package Cache
        keys:
        - npm-packages3-{{ checksum "package-lock.json" }}
    - run: npm i
    - save_cache:
        name: Save NPM Package Cache
        key: npm-packages3-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
